### ISSUE TITLE
Missing border on 2nd featured card image

### ISSUE THREAD

**Issue by RachelRVasquez** [JDRF/design-system#102]
http://jdrf.github.io/design-system/dist/components.html#cards

There's a 1px border around the image in the 2nd featured card image in the designs. We'll need to implement it into the DS.

![screen shot 2016-06-13 at 2 48 23 pm](https://cloud.githubusercontent.com/assets/10246844/16019449/14c27b2c-3177-11e6-830a-ddf3ff645dbd.png)

**Comment by RachelRVasquez** [comment]
@fuhton PR submitted:

https://github.com/JDRF/design-system/pull/103

**Comment by fuhton** [comment]
Merged and confirmed.
