### ISSUE TITLE
Adjustments to 2nd featured card .ds-card-block

### ISSUE THREAD

**Issue by RachelRVasquez** [JDRF/design-system#106]
In the 2nd featured card, the space from the right edge of the image and the content next to it is 24px according to the design. However due to doubling the `.ds-card-block` wrappers, we're doubling the padding. We also need to adjust the percentages slightly so the image is at full size (286px) at it's largest breakpoint.

This is also a good opportunity to have less markup and remove the `.ds-card-block` wrappers and just tack the class directly on `.ds-card-hero-block`.

Let's update the scss to this in addition to considerations for mobile:

```
.ds-card-featured .ds-card-hero-block-1 {
    width: 49%;
    padding-right: 0;
}
```

**Comment by RachelRVasquez** [comment]
@fuhton 

Submitted two PRs to bring this card closer to designs padding wise and with that third column. Also removed an extra div we didn't have to use.

https://github.com/JDRF/design-system/pull/107

https://github.com/JDRF/design-system/pull/108

**Comment by fuhton** [comment]
Merged and confirmed.
