### ISSUE TITLE
Design System - Buttons - Width and Height

### ISSUE THREAD

**Issue by jdrf-digitaldesigner** [JDRF/design-system#109]
The width and height of the buttons should be multiples of 4, with the following heights:

- 32px (small buttons)

- 40px (medium buttons)

- 48px (large buttons)

Thx,

Ismael

**Comment by RachelRVasquez** [comment]
@jdrf-digitaldesigner Currently implementing the heights to the buttons. As for the widths, we'd advise against setting fixed widths on the buttons as we can't predict the content of the buttons. To ensure all content will fit inside the buttons without restrictions, let's leave the width defined by the padding and when used in projects, custom styles can overwrite on a case by case basis.

cc: @fuhton

**Comment by RachelRVasquez** [comment]
@fuhton 

PR submitted:

https://github.com/JDRF/design-system/pull/120

**Comment by fuhton** [comment]
Merged

**Comment by fuhton** [comment]
@jdrf-digitaldesigner Can you review and confirm?

**Comment by fuhton** [comment]
@jdrf-digitaldesigner Can you review and confirm?

**Comment by jdrf-digitaldesigner** [comment]
Confirmed. Thx!
