### ISSUE TITLE
All: Sidebar navigation 'current' page text should be blue (see img / comments)

### ISSUE THREAD

**Issue by McCallumDillon** [JDRF/design-system#11]
Our sidebar navigation 'current' page text should be blue per the Zeplin example.

See screenshot of "Zeplin" example on the left and "live site" on the right.

![sidebarnav](https://cloud.githubusercontent.com/assets/5239235/15620370/ae69918c-240e-11e6-9ac5-db7c81984415.jpg)

* Interestingly enough in the side by side comparison the "blue" color tone of the text 'appears' to be slightly different (live site being darker) - however after inspecting each element I show the proper and matching Hex value for both.

**Comment by RachelRVasquez** [comment]
@fuhton 

PR submitted for this fix: https://github.com/JDRF/design-system/pull/20

**Comment by fuhton** [comment]
Merged.
