### ISSUE TITLE
Design System - Outline Buttons - Remove Shadow

### ISSUE THREAD

**Issue by jdrf-digitaldesigner** [JDRF/design-system#110]
The Outline buttons should not have the box shadow property applied to them.

Thx,

Ismael

**Comment by RachelRVasquez** [comment]
@fuhton 

Created a PR:

https://github.com/JDRF/design-system/pull/121

**Comment by fuhton** [comment]
Merged.

**Comment by fuhton** [comment]
@jdrf-digitaldesigner Can you review and confirm?

**Comment by jdrf-digitaldesigner** [comment]
Confirmed. Thx!
