### ISSUE TITLE
Design System Version Info

### ISSUE THREAD

**Issue by pmmck** [JDRF/design-system#111]
I don't see where I can find information about which version of the DS I'm using.  I expect the DS to evolve faster than JDRF sites upgrading to the current version, so having a clear way of identifying which version a site is using is important.

**Comment by pmmck** [comment]
What version should we launch with?  It seems like it's further along than the current status of v0.0.1.  thoughts?  

@fuhton @RachelRVasquez @briansaycocie

**Comment by fuhton** [comment]
Working on a build tool. On launch 0.5.0

**Comment by fuhton** [comment]
@pmmck This is merged and ready for a review. 

[css](https://github.com/JDRF/design-system/blob/master/dist/css/design-system.css)
[js](https://github.com/JDRF/design-system/blob/master/dist/js/design-system.js)

They're both the same header.

**Comment by pmmck** [comment]
@fuhton `JDRF Design System for managing styles` should be `JDRF Digital Design System for building official JDRF websites` 

Is that too long?  It's more than just managing styles, because we already have components and will be adding patterns and templates.   And this can't be used unless the project is approved by JDRF.

**Comment by fuhton** [comment]
It's 6 characters too long in my opinion.

**Comment by pmmck** [comment]
Let's drop the explanation and just use `JDRF Digital Design System`

**Comment by fuhton** [comment]
Merged. @pmmck Confirm?

**Comment by pmmck** [comment]
LGTM.
