### ISSUE TITLE
Design System - Text Buttons - Reduce L/R Padding

### ISSUE THREAD

**Issue by jdrf-digitaldesigner** [JDRF/design-system#114]
The Left and Right padding on Text buttons should be reduced to 8px.

Thx,

Ismael

**Comment by RachelRVasquez** [comment]
@jdrf-digitaldesigner 

I took a look at the design - it looks like the text buttons are following the padding set on other buttons (16px). Can you confirm this is what's expected?

![screen shot 2016-06-14 at 1 23 43 pm](https://cloud.githubusercontent.com/assets/10246844/16052698/5b480f78-3233-11e6-8957-a1bf1c147c66.png)

![screen shot 2016-06-14 at 1 23 51 pm](https://cloud.githubusercontent.com/assets/10246844/16052702/5f9a7552-3233-11e6-87ac-b50c4cc7d10a.png)

Thanks.

cc: @fuhton

**Comment by jdrf-digitaldesigner** [comment]
@RachelRVasquez 

We've had to update to ensure that the hover background wouldn't touch the edge in cards. Thx

**Comment by RachelRVasquez** [comment]
@fuhton 

PR submitted:

https://github.com/JDRF/design-system/pull/148

**Comment by fuhton** [comment]
Merged.

**Comment by fuhton** [comment]
@jdrf-digitaldesigner Can you review and confirm?

**Comment by jdrf-digitaldesigner** [comment]
Confirmed. Thx!
