### ISSUE TITLE
Design System - Button Group Toggles - Not Functioning Properly

### ISSUE THREAD

**Issue by jdrf-digitaldesigner** [JDRF/design-system#116]
The Button Groups should display one selected button at a time (Toggle Segment style)

**Comment by RachelRVasquez** [comment]
@jdrf-digitaldesigner @pmmck 

Left a comment on this issue to clarify expected functionality:

https://github.com/JDRF/design-system/issues/117

**Comment by RachelRVasquez** [comment]
@pmmck @jdrf-digitaldesigner Does this function like the button toolbar as well?

**Comment by pmmck** [comment]
@RachelRVasquez the Button Group in the DS should function like the Button Group in Bootstrap: http://v4-alpha.getbootstrap.com/components/button-group/#basic-example

@jdrf-digitaldesigner

**Comment by RachelRVasquez** [comment]
@fuhton 

Submitted a PR:

https://github.com/JDRF/design-system/pull/154

**Comment by fuhton** [comment]
@RachelRVasquez This makes the button groups not work correctly.

**Comment by fuhton** [comment]
Confirmed to work the same as http://v4-alpha.getbootstrap.com/components/button-group/#basic-example

**Comment by jdrf-digitaldesigner** [comment]
Confirmed. Thx!
