### ISSUE TITLE
Design System - Checkbox and Radio Buttons Margins

### ISSUE THREAD

**Issue by jdrf-digitaldesigner** [JDRF/design-system#118]
There should be an 8px margin between each button for Checkbox and Radio Buttons.

Thx,

Ismael

**Comment by RachelRVasquez** [comment]
@fuhton 
Submitted two PRs:

https://github.com/JDRF/design-system/pull/131

https://github.com/JDRF/design-system/pull/132

**Comment by fuhton** [comment]
Merged.

**Comment by fuhton** [comment]
@jdrf-digitaldesigner Can you review and confirm?

**Comment by jdrf-digitaldesigner** [comment]
Confirmed. Thx!
