### ISSUE TITLE
All: Left rail 'search form' improvements (see comments)

### ISSUE THREAD

**Issue by McCallumDillon** [JDRF/design-system#12]
-  styling to match Zeplin form styles found here : https://app.zeplin.io/project.html#pid=55a514081c757ce422fceb60&sid=573a1b648967de084209e491

- Currently the only way to 'search' is by pressing 'enter' - there is no search text or search icon to 'submit' the search. Ideally we'd place a search/submit icon inside the input field on the right.

**Comment by fuhton** [comment]
Styling will be left until the forms project is underway. Search is now disabled by default when selecting `enter` per #29

**Comment by fuhton** [comment]
This is closed now. The initial request is out of scope and the second has been addressed.
