### ISSUE TITLE
Design System - Cards - Remove Border

### ISSUE THREAD

**Issue by jdrf-digitaldesigner** [JDRF/design-system#123]
Please remove 1px Border value.
![screen shot 2016-06-14 at 12 31 24 pm](https://cloud.githubusercontent.com/assets/19931482/16051027/fdcfa88a-322b-11e6-9065-cdd7d4a9cdf5.png)

**Comment by fuhton** [comment]
Merged.

@jdrf-digitaldesigner Please review and confirm.

**Comment by jdrf-digitaldesigner** [comment]
Confirmed. Thx!
