### ISSUE TITLE
Design System - Featured Cards Aspect Ratio

### ISSUE THREAD

**Issue by jdrf-digitaldesigner** [JDRF/design-system#124]
The aspect ratio of the images on cards should be 13:8.

Thx,

Ismael

**Comment by briansaycocie** [comment]
Hey @jdrf-digitaldesigner,

I've updated the dimensions of the Featured card image to 13:8 (converted into pixels would be 520 x 320). Visually, it looks the same as the current version, but I wanted to note the Featured card example is squeezed together in the main content column which does not reflect the actual use of the card (which I believe is full width). I've added a screenshot to compare the two:

![13x8_aspect_ratio](https://cloud.githubusercontent.com/assets/1328262/16061090/ec2ef69c-3250-11e6-8950-82ce4a03f54e.jpg)

As a future enhancement, we can look into a way to display the card full width as it's intended.

cc: @fuhton

**Comment by pmmck** [comment]
@briansaycocie that's a good point and I'm not sure how to get around that.  @jdrf-digitaldesigner and I will discuss tomorrow.  Would love to hear @fuhton 's thoughts.

**Comment by fuhton** [comment]
Unfortunately, we're not in a position to change the width of the content - it would require rebuilding the sidebar nav. This would be best as a future enhancement

**Comment by jdrf-digitaldesigner** [comment]
Confirmed. Thx!

**Comment by fuhton** [comment]
Merged.

@jdrf-digitaldesigner Please review and confirm.
