### ISSUE TITLE
Design System - Featured Card Header Height

### ISSUE THREAD

**Issue by jdrf-digitaldesigner** [JDRF/design-system#126]
The height of the Featured Card's Header should be 48px, with 16px top and bottom padding. 

Thx,

Ismael

**Comment by RachelRVasquez** [comment]
Let's avoid adding a fixed height on the header to compensate for longer titles or screen sizes where titles may break into multiple lines. We can move forward with adjusting the padding.

**Comment by pmmck** [comment]
@RachelRVasquez 
The padding and line-height should equal 48px (for a single line title).  We agree that the solution is not to declare a fixed height.

cc @jdrf-digitaldesigner

**Comment by fuhton** [comment]
Merged. @jdrf-digitaldesigner @pmmck Please review.

**Comment by jdrf-digitaldesigner** [comment]
The Featured Cards' Headers still show up as 41px high. Thx

**Comment by fuhton** [comment]
Merged. @jdrf-digitaldesigner @pmmck Please review.

**Comment by jdrf-digitaldesigner** [comment]
Almost. It now comes up at 49px

**Comment by briansaycocie** [comment]
@jdrf-digitaldesigner it appears the border is causing the additional pixel. When I inspect the element and apply a value of 0, I get 48px tall. Thoughts?

![screenshot 2016-06-16 14 05 42](https://cloud.githubusercontent.com/assets/1328262/16129747/aa84ec34-33cb-11e6-9a7f-45172e53b135.png)

**Comment by fuhton** [comment]
@jdrf-digitaldesigner 

@briansaycocie 's answer seems completely within the realm of reason and acceptability.

**Comment by jdrf-digitaldesigner** [comment]
That makes, but could we place it along the bottom edge of the cell, instead of outside? We could use this as a convention for all Dividers.

![screen shot 2016-06-16 at 3 18 00 pm](https://cloud.githubusercontent.com/assets/19931482/16130127/c1cf19f0-33d5-11e6-95e9-cd2299f0f545.png)

**Comment by fuhton** [comment]
@jdrf-digitaldesigner @pmmck I think it comes down to if this is possible with how we've integrated with Bootstrap. If there's a convention in Bootstrap that we're following - then the answer is no. But if we're doing this "because" and Bootstrap has the ability to allow us to implement your suggestion, then we should follow your suggestion.

cc @briansaycocie

**Comment by jdrf-digitaldesigner** [comment]
Understood. Let's keep them at 49px. Thx!
