### ISSUE TITLE
Design System - Featured Card Divider

### ISSUE THREAD

**Issue by jdrf-digitaldesigner** [JDRF/design-system#127]
The Featured Card's Divider should not extend beyond the start of the Header text (starting from the right edge).

Thx,

Ismael

**Comment by briansaycocie** [comment]
Hey Ismael,

Can you provide a screenshot of the divider? I'm having trouble viewing the issue.

Thanks,
Brian

**Comment by pmmck** [comment]
Hi @briansaycocie ,

Here you go: https://www.evernote.com/l/ABffiNs0jiVNjps78cPcnjGnjjYXLIqfF9s

cc @jdrf-digitaldesigner

**Comment by fuhton** [comment]
Merged.

@jdrf-digitaldesigner Please review and confirm.

**Comment by jdrf-digitaldesigner** [comment]
Please change border-bottom-width to: 1px, and color to: #E0E0E0. Thx

**Comment by fuhton** [comment]
Merged. @jdrf-digitaldesigner @pmmck Please review.

**Comment by jdrf-digitaldesigner** [comment]
Confirmed. Thx!
