### ISSUE TITLE
Design System - Featured Card Footer

### ISSUE THREAD

**Issue by jdrf-digitaldesigner** [JDRF/design-system#129]
The Featured Card Footer should have a 24px top padding from the bottom of the Content Area, and an 8px bottom padding to the bottom edge of the Card. 

Thx,

Ismael

**Comment by fuhton** [comment]
Merged. @jdrf-digitaldesigner @pmmck Please review.

**Comment by jdrf-digitaldesigner** [comment]
Confirmed. Thx!
