### ISSUE TITLE
Design System - Featured Card - Responsive Issue

### ISSUE THREAD

**Issue by jdrf-digitaldesigner** [JDRF/design-system#134]
Please look into the format of the Featured card when the browser window hits 1200px (CTA goes away) and 992px (Card loses structure).

Thx,

Ismael

**Comment by fuhton** [comment]
Merged. @jdrf-digitaldesigner @pmmck Please review.

**Comment by jdrf-digitaldesigner** [comment]
Looks good, but can we keep the “ds-btn-link” Buttons left-justified <768? Thx

**Comment by pmmck** [comment]
Link buttons don't have the same responsive behavior as the other buttons.  They don't change width and they don't change alignment.

**Comment by fuhton** [comment]
Merged. @jdrf-digitaldesigner @pmmck Please review.

**Comment by jdrf-digitaldesigner** [comment]
Please update the “ds-btn-link” Buttons' alignment (8px from Left border) on the following Cards:
phantom-ds-card-content-type-title-subtitle-image-text-links

phantom-ds-card-content-type-title-text-links

Thx,

Ismael

**Comment by briansaycocie** [comment]
Link button alignment resolved in this PR" #229

**Comment by fuhton** [comment]
Merged. @jdrf-digitaldesigner  Confirm?

**Comment by jdrf-digitaldesigner** [comment]
Confirmed. Thx!
