### ISSUE TITLE
Design System - Featured Card 

### ISSUE THREAD

**Issue by jdrf-digitaldesigner** [JDRF/design-system#135]
The Header text's top and bottom padding  for **ds-card ds-card-featured** should be 12px.

The Image should only say "Image", please remove "cap".

The Image's bottom padding should be 32px.

Title color should be: #002855

Padding between Title and Date: 12px

Padding between Date and Location: 12px

Padding between Location and CTA: 16px

*Date-range and Location icons missing

Thx,

Ismael
![screen shot 2016-06-14 at 3 47 40 pm](https://cloud.githubusercontent.com/assets/19931482/16057285/65fe20f6-3247-11e6-8e9f-10d6bb7269be.png)

**Comment by pmmck** [comment]
@jdrf-digitaldesigner 

I'm realizing now that this probably isn't the best example to use for the Design System documentation.  This particular case with the "disclaimer intro copy" is is a variation specific to the Promotions That Give Back content.  And we can probably achieve the style variation using <small> and .muted.  

thoughts?

cc @RachelRVasquez @fuhton

**Comment by jdrf-digitaldesigner** [comment]
@pmmck 

This makes sense on my end, as long as we're able to set the Content Area to a two-column layout. Thx

**Comment by pmmck** [comment]
@jdrf-digitaldesigner so perhaps this is an example of a card without a header or footer and a rich layout inside?  We could just remove the disclaimer piece from this.

cc @RachelRVasquez  @fuhton

**Comment by fuhton** [comment]
Merged. @jdrf-digitaldesigner @pmmck Please review.

**Comment by jdrf-digitaldesigner** [comment]
Please remove "ds-card-header"

Update margin between the two "ds-card-subtitle" elements: 12px

Update Location icon to "Location-on" icon

Thx,

Ismael

**Comment by fuhton** [comment]
Merged. @jdrf-digitaldesigner @pmmck Please review.

**Comment by jdrf-digitaldesigner** [comment]
Confirmed. Thx!
