### ISSUE TITLE
Design System - Cards - Image Cap Card

### ISSUE THREAD

**Issue by jdrf-digitaldesigner** [JDRF/design-system#136]
ds-card-img-top

Image: Use 13:8 Aspect Ratio

Content Area: Left and Right Padding 16px

Date: Top Padding 16px, Bottom Padding 8px

Thx,

Ismael

**Comment by fuhton** [comment]
Merged. @jdrf-digitaldesigner Ready for you to re-review

**Comment by jdrf-digitaldesigner** [comment]
Can you please remove the "ds-card-subtitle" padding-top? Thx

**Comment by briansaycocie** [comment]
Resolved in these PRs: #199 and #200

**Comment by fuhton** [comment]
Merged. @pmmck @jdrf-digitaldesigner Please review.

**Comment by jdrf-digitaldesigner** [comment]
The padding-top on "phantom-ds-card-image-cap" needs to be removed. Thx

**Comment by fuhton** [comment]
Merged. @jdrf-digitaldesigner @pmmck Confirm?

**Comment by jdrf-digitaldesigner** [comment]
Confirmed. Thx!
