### ISSUE TITLE
Design System - Cards Organization

### ISSUE THREAD

**Issue by jdrf-digitaldesigner** [JDRF/design-system#138]
Image Cap:
ds-card-img-top

Header and Footer:
ds-card ds-card-featured ds-card-featured-hero
ds-card ds-card-featured
ds-card ds-card-content
ds-card-title ds-h4
ds-card ds-card-block
ds-card ds-card-program

Thx,

Ismael

**Comment by briansaycocie** [comment]
Hey @jdrf-digitaldesigner,

Would you like to move the Image Cap card example above the Featured Hero card? Can you elaborate a bit on the organization?

Thanks!
Brian

**Comment by jdrf-digitaldesigner** [comment]
@briansaycocie 

Yes. We would start with the Image Cap Card examples, and then follow with the others as they are all Cards with Header and/or Footer in essence. Does that help, or should I provide IDs? Let me know.

Thx,

Ismael

**Comment by briansaycocie** [comment]
Great! IDs would be fantastic. Thanks!

**Comment by jdrf-digitaldesigner** [comment]
**Image Cap:**
phantom-ds-card-image-cap

phantom-ds-card-content-type-image-title-text-button

phantom-ds-card-content-type-image-title-text-list-links

phantom-ds-card-content-type-image-text

**Header and Footer:**
phantom-ds-card-featured-hero

phantom-ds-card-featured

phantom-ds-card-content-header-footer

phantom-ds-card-content-header

phantom-ds-card-content-type-title-subtitle-image-text-links

phantom-ds-card-content-type-title-text-links

phantom-ds-card-content-type-program

Thx,

Ismael

**Comment by fuhton** [comment]
Merged. @jdrf-digitaldesigner @pmmck Please review.

**Comment by jdrf-digitaldesigner** [comment]
Confirmed. Thx!
