### ISSUE TITLE
Design System - Content Cards

### ISSUE THREAD

**Issue by jdrf-digitaldesigner** [JDRF/design-system#139]
ds-card ds-card-content

Padding between Content Text and image: 24px

Remove "cap" from Image

Padding between Image and CTA: 32px

Padding between CTA and bottom edge of Card: 32px

*For the Location Card: Add Launch icon and remove underline on "Directions" text link

Thx,

Ismael

**Comment by briansaycocie** [comment]
@jdrf-digitaldesigner Would you prefer if the copy "cap" was removed for all images? Or specifically for Content Cards? Just wanted to double check. Thanks!

**Comment by jdrf-digitaldesigner** [comment]
Removing it from the following Cards:
phantom-ds-card-featured

phantom-ds-card-content-header-footer

phantom-ds-card-content-header

phantom-ds-card-content-type-title-subtitle-image-text-links

Thx,

Ismael

**Comment by briansaycocie** [comment]
Perfect, thanks!

**Comment by fuhton** [comment]
Merged. @jdrf-digitaldesigner Ready for you to re-review

**Comment by jdrf-digitaldesigner** [comment]
Can you please remove it from phantom-ds-card-content-header? Thx

**Comment by fuhton** [comment]
Merged. @jdrf-digitaldesigner Please confirm.

**Comment by jdrf-digitaldesigner** [comment]
Confirmed. Thx!
