### ISSUE TITLE
Location card strong text color

### ISSUE THREAD

**Issue by RachelRVasquez** [JDRF/design-system#144]
Text color on the location card for `<strong>` elements should be `rgba(0, 0, 0, 0.87);` instead of black.
![screen shot 2016-06-14 at 5 17 41 pm](https://cloud.githubusercontent.com/assets/10246844/16060063/eb3d3c6e-3253-11e6-9b99-9e0588d9b798.png)

**Comment by RachelRVasquez** [comment]
@fuhton 

Submitted PR:

https://github.com/JDRF/design-system/pull/145

**Comment by fuhton** [comment]
Merged.
