### ISSUE TITLE
Customize the order of items in the Fabricator Menu

### ISSUE THREAD

**Issue by pmmck** [JDRF/design-system#149]
It would be nice to control the order of Layout, Content, Components as well as their sub items based on JDRF priority / popular usage rather than alphabetical.

**Comment by RachelRVasquez** [comment]
@fuhton Commented on the PR.

**Comment by RachelRVasquez** [comment]
@fuhton Merged.

**Comment by fuhton** [comment]
@pmmck Please confirm this is the correct order.

**Comment by pmmck** [comment]
@fuhton can we manually add each item into the menu?  I'd like to take the same approach Bootstrap does with prioritizing based on popularity / importance.

**Comment by fuhton** [comment]
@pmmck That sounds smart. Should we follow the exact same hierarchy as v4 bootstrap?

**Comment by pmmck** [comment]
Grid
Elevation

Color
Typography
Icons

Buttons
Forms
Cards
Side Navigation
Badges

**Comment by fuhton** [comment]
@pmmck This has been pushed with the requested sorting.
