### ISSUE TITLE
ALL: Buttons (see comments / screenshot)

### ISSUE THREAD

**Issue by McCallumDillon** [JDRF/design-system#15]
I imagine our 'buttons' should have some rule around the margin surrounding the button.

See this screenshot : 
![screen shot 2016-05-27 at 2 56 56 pm](https://cloud.githubusercontent.com/assets/5239235/15622189/7773a750-241b-11e6-88a8-4ea319bf0984.jpg)

Zeplin (on the left) has some horizontal left/right spacing- we may want something along these lines by default for our buttons. (screenshot shows github on right)

Zeplin also shows "gotham medium" for the button text when github shows gotham book - granted I think 'book' looks better here we should likely adhear to the approved Zeplin specifics.

**Comment by RachelRVasquez** [comment]
@fuhton 

PR submitted for this issue:

https://github.com/JDRF/design-system/pull/21

**Comment by fuhton** [comment]
Merged.

**Comment by RachelRVasquez** [comment]
@fuhton 

Submitted a PR with this change only:

https://github.com/JDRF/design-system/pull/24

**Comment by fuhton** [comment]
Merged. Will review locally.

**Comment by fuhton** [comment]
Looks good.

**Comment by McCallumDillon** [comment]
buttons should be “gotham medium” font weight - on our stage we have them as “book” still

**Comment by McCallumDillon** [comment]
Also just noticed that "button outlines" should have a 2px border instead of the current 1px.

![screen shot 2016-05-31 at 12 28 58 pm](https://cloud.githubusercontent.com/assets/5239235/15687795/6dbd2b10-272b-11e6-840e-27c26b936ac5.jpg)

**Comment by McCallumDillon** [comment]
Our toggle segment/icon styling is off.

For theToggle Segment: Zeplin shows white bg, with green border color. "selected" state shows the green bg.
For the Toggle Icon Bar: Zeplin shows default state with the white bg. "selected" state shows the darker gray background.
![screen shot 2016-05-31 at 12 38 58 pm](https://cloud.githubusercontent.com/assets/5239235/15688026/eca00cc6-272c-11e6-81ff-e17e2a5c4c6e.jpg)

Staging just shows the 'gray bg' at all times for both:
![screen shot 2016-05-31 at 12 39 01 pm](https://cloud.githubusercontent.com/assets/5239235/15688040/f9ba2ff4-272c-11e6-9493-d2e378b9f3d9.jpg)

**Comment by fuhton** [comment]
Toggling isn't complete yet. I'll be adding the JS to make it work correctly in #18 .


@RachelRVasquez Let's address @McCallumDillon 's other two comments.

**Comment by fuhton** [comment]
I'll be taking over all work regarding this ticket.

**Comment by RachelRVasquez** [comment]
@McCallumDillon @fuhton 

The styles should be correct on staging now - the PR just needed to be merged in.

https://github.com/JDRF/design-system/issues/15

**Comment by RachelRVasquez** [comment]
@McCallumDillon Will create another PR for the border width on buttons.

**Comment by fuhton** [comment]
Outline is correct now. Toggling moved to a new ticket.
