### ISSUE TITLE
Color variable names

### ISSUE THREAD

**Issue by pmmck** [JDRF/design-system#152]
Change:

`$primary-blue: #0073cf;
$primary-dark-blue: #002855;`

to:

`$jdrf-blue: #0073cf;
$jdrf-dark-blue: #002855;`

Which means we no longer need:

`$jdrf-blue: $primary-blue;`

And this can be changed from: `$brand-primary: $primary-blue;` to `$brand-primary: $jdrf-blue;`

**Comment by RachelRVasquez** [comment]
@fuhton PRs:

https://github.com/JDRF/design-system/pull/210

https://github.com/JDRF/design-system/pull/211

**Comment by fuhton** [comment]
Merged. @pmmck Please confirm.

**Comment by pmmck** [comment]
LGTM.
