### ISSUE TITLE
Text Colors

### ISSUE THREAD

**Issue by pmmck** [JDRF/design-system#153]
After spending some more time with these rgba colors, we think it's best to use HEX for all.  The exception being the reversed text.  A transparent white makes the most sense there.

Change: `$jdrf-black: #000000;` To `$jdrf-black: #212121;`

Change:

```
$text-primary: rgba(0, 0, 0, 0.87);
$text-secondary: rgba(0, 0, 0, 0.54);
$text-disabled: rgba(0, 0, 0, 0.38);
$text-dividers: rgba(0, 0, 0, 0.12);
```

To:

```
$text-primary: $jdrf-black;
$text-secondary: $grey-7;
$text-disabled: $grey-6;
$text-dividers: $grey-4;
```

cc @jdrf-digitaldesigner

**Comment by RachelRVasquez** [comment]
@fuhton 

PR: https://github.com/JDRF/design-system/pull/207

**Comment by fuhton** [comment]
Merged. @jdrf-digitaldesigner @pmmck Confirm?

**Comment by pmmck** [comment]
LGTM.
