### ISSUE TITLE
H3.f-example-title to 'dark blue' (see comments)

### ISSUE THREAD

**Issue by McCallumDillon** [JDRF/design-system#16]
Lets change the .f-example-title h3s to be the dark blue (#002855) color to better emulate the title scheme of Zeplin. All of their element titles are in that dark blue instead of the black we have on ours.

**Comment by RachelRVasquez** [comment]
I've made this change on a previous PR. It looks like I can't submit multiple PRs since I'm working directly on gh-pages. @fuhton Do we want to work on separate branches for the sake of PRs?

Here's where the change is: https://github.com/JDRF/design-system/pull/21

**Comment by fuhton** [comment]
Merged.

**Comment by RachelRVasquez** [comment]
@fuhton 

Created a separate PR for this change only:

https://github.com/JDRF/design-system/pull/25

**Comment by fuhton** [comment]
Merged and looks good.
