### ISSUE TITLE
Design System - Cards - ds-card-img-top

### ISSUE THREAD

**Issue by jdrf-digitaldesigner** [JDRF/design-system#161]
.f-example .ds-card - Update max-width to remove white gap on right side (also happens on "ds-card-block")
![screen shot 2016-06-15 at 11 24 45 am](https://cloud.githubusercontent.com/assets/19931482/16085944/cf5e4ee6-32eb-11e6-88a6-d66433fe4b3c.png)

ds-card-block - Update T, B, L, R Padding: 16px

ds-card-title - Update margin-bottom: 16px

ds-card-text - Update margin-bottom: 16px

ds-btn - Update margin-bottom: 8px

Thx,

Ismael

**Comment by fuhton** [comment]
Merged. @jdrf-digitaldesigner Please confirm.

**Comment by jdrf-digitaldesigner** [comment]
Confirmed. Thx!
