### ISSUE TITLE
Elevation Mixins

### ISSUE THREAD

**Issue by pmmck** [JDRF/design-system#163]
A few thoughts:

```
@mixin elevation-remove()
```
Don't we use "no-*" as the naming convention for this sort of thing?  So it would be `no-elevation`?

--

The opacities seem to be rounding up and down.  Is there a reason why, for example, `rgba(0, 0, 0, 0.2)` is being used instead of `rgba(0, 0, 0, 0.24)`?

**Comment by RachelRVasquez** [comment]
@pmmck Is this based on the class we use for ripple? http://jdrf.github.io/design-system/dist/components.html#buttons

We haven't set it as a standard, but we can go either way (remove/no) to create one.

As for the opacities, I believe they were set early on and possibly changed so I'll check to see if we missed any of the older styles for updates.

cc: @fuhton

**Comment by pmmck** [comment]
@RachelRVasquez ah, yes, the `.no-ripple` is what I was thinking of.   `.no-ripple` or `.ripple-remove` seems like a personal preference.  I'd just like us to be consistent about it.

**Comment by RachelRVasquez** [comment]
@fuhton 

PRs submitted and classes set to "no".

https://github.com/JDRF/design-system/pull/205

https://github.com/JDRF/design-system/pull/206

**Comment by fuhton** [comment]
Merged. @pmmck Confirm?

**Comment by RachelRVasquez** [comment]
@fuhton Another PR has been submitted for master: https://github.com/JDRF/design-system/pull/222

**Comment by fuhton** [comment]
Merged. @pmmck Confirm?

**Comment by pmmck** [comment]
LGTM.
