### ISSUE TITLE
Design System - Cards - ds-card w/header and footer

### ISSUE THREAD

**Issue by jdrf-digitaldesigner** [JDRF/design-system#164]
id=phantom-ds-card-content-type-title-subtitle-image-text-links

Header padding - Update T, B, L, R Padding: 16px

ds-card-text - Update T, L, R Margins: 16px, Bottom Margin: 8px

Use "ds-btn ds-btn-link" instead of current "ds-card-link

ds-btn ds-btn-link - Update T, L, R Margins: 8px, Bottom Margin: 12px

*Remove "cap" from image

Thx,

Ismael

**Comment by briansaycocie** [comment]
@jdrf-digitaldesigner I believe these have been resolved from previous tickets. Can you confirm?

**Comment by jdrf-digitaldesigner** [comment]
Confirmed. Thx!
