### ISSUE TITLE
Design System - Cards - phantom-ds-card-content-type-title-text-links

### ISSUE THREAD

**Issue by jdrf-digitaldesigner** [JDRF/design-system#165]
ds-card-title - Update T, L, R Margins: 16px, Bottom Margin: 8px

ds-card-text - Update L, R Margins: 16px

Use "ds-btn ds-btn-link" instead of current "ds-card-link

ds-btn ds-btn-link - Update T, L, R Margins: 8px, Bottom Margins: 12px

Thx,

Ismael

**Comment by RachelRVasquez** [comment]
@fuhton 

PR submitted: https://github.com/JDRF/design-system/pull/182

**Comment by fuhton** [comment]
Merged. @jdrf-digitaldesigner Can you review?

**Comment by jdrf-digitaldesigner** [comment]
Update "ds-card-title" to H3 size and color

Update "ds-card-title" margin-bottom: 8px

Update "ds-card-text" margin-bottom: 8px

Place both "ds-btn ds-btn-link" Buttons on the same line, move 8px to the left, and remove margin-bottom

Update "ds-card ds-card-block" padding-bottom: 12px

Thx,

Ismael

**Comment by RachelRVasquez** [comment]
@jdrf-digitaldesigner  @pmmck 

I've completed the first three changes but have a question about the last two:

> Place both "ds-btn ds-btn-link" Buttons on the same line, move 8px to the left, and remove margin-bottom

Are we trying to align the buttons to the left of the card with the rest of the content? In this case - do we want to stick with using button styles for this card or keep them as regular links? Assuming that this card can be filled in various ways, I want to prevent adding styles to this specific case that may break other cases or affect other cards. Perhaps we want to create a class where only these changes only apply if the card is set up this exact way?

> Update "ds-card ds-card-block" padding-bottom: 12px

This seems like a similar case as the first one where our links being buttons and having that extra padding is causing us to change styles for this specific case to compensate. Do we want to have 12px on the bottom of all cards or only if a card is set up this specific way?

cc: @fuhton

**Comment by jdrf-digitaldesigner** [comment]
> Place both "ds-btn ds-btn-link" Buttons on the same line, move 8px to the left, and remove margin-bottom

We're trying to achieve the same structure as "phantom-ds-card-content-type-image-title-text-list-links" where the buttons are positioned 8px from the left border in order for the Button Labels to align with the other text elements, in the card.

<img width="346" alt="screen shot 2016-06-16 at 9 13 05 am" src="https://cloud.githubusercontent.com/assets/19931482/16117928/9c71ecd8-33a2-11e6-9883-bd2d6ec5637f.png">


> Update "ds-card ds-card-block" padding-bottom: 12px

The padding will vary depending on the components displayed at the bottom of the card, so I wouldn't apply this rule to every card.

**Comment by fuhton** [comment]
@pmmck @jdrf-digitaldesigner Let's here your thoughts.

**Comment by fuhton** [comment]
@RachelRVasquez We're not using the DS properly here. If we add this HTML it sorts properly.


````
<div class="ds-card">
        <div class=" ds-card-block">
            <h3 class="ds-card-title ds-h4">Card title</h3>
            <p class="ds-card-text">etc...</p>

        </div>
        <div class="ds-card-block ds-card-block-btns">
             <a href="#!" class="ds-btn ds-btn-link ds-has-ripple">Card link</a>
             <a href="#!" class="ds-btn ds-btn-link ds-has-ripple">Another link</a>
        </div>
</div>
````

**Comment by RachelRVasquez** [comment]
@fuhton gh-pages PR updated with markup change.

**Comment by fuhton** [comment]
@RachelRVasquez Branch has an open comment and merge issues.

**Comment by RachelRVasquez** [comment]
@fuhton PRs merge conflicts have been resolved.

**Comment by fuhton** [comment]
Merged. @jdrf-digitaldesigner @pmmck Confirm?

**Comment by jdrf-digitaldesigner** [comment]
Remove ds-card-block padding-bottom

Update ds-card-title to $jdrf-dark-blue

Thx,

Ismael

**Comment by pmmck** [comment]
@jdrf-digitaldesigner the blue title is a function of being linked in our Promotions designs, correct?  Or is the intention that all cards will have blue titles regardless of the site's interactive color?

cc @fuhton

**Comment by jdrf-digitaldesigner** [comment]
@pmmck 

Correct. However this style of card does not have a clickable title in the Bootstrap example, which is why I mentioned the dark blue, which we use on non-clickable links.

**Comment by pmmck** [comment]
@jdrf-digitaldesigner sorry, I missed that.  thanks!

**Comment by RachelRVasquez** [comment]
@pmmck @jdrf-digitaldesigner 

Just wanted to clarify what the task is - we're removing the padding bottom for `.ds-card-block` on this specific card and we're ensuring all the `.ds-card-title` for all cards are a dark blue because they're not links. Otherwise if they are links, they'd be the lighter blue we see in Promotions?

**Comment by jdrf-digitaldesigner** [comment]
Correct on padding-bottom. But dark blue title only for this card. Thx

**Comment by RachelRVasquez** [comment]
@jdrf-digitaldesigner Just removed the padding bottom on `.ds-card-block` locally for this card and I'm seeing the link buttons touching the bottom of the card. Let's keeping the padding on the `.ds-card-block` wrapping the buttons to prevent that from happening. Thoughts?

![screen shot 2016-06-17 at 4 04 52 pm](https://cloud.githubusercontent.com/assets/10246844/16163146/ad1f44e6-34a5-11e6-89d6-db9db1aa4ab8.png)

**Comment by RachelRVasquez** [comment]
@fuhton Title color updated globally. When links are placed within the card titles, they will turn the lighter blue.

https://github.com/JDRF/design-system/pull/255

Should we update some of the markup on some cards to reflect this as well?

**Comment by jdrf-digitaldesigner** [comment]
@RachelRVasquez Please revert to last version with padding-bottom on card-block, as having the buttons touch the bottom edge of the card wouldn't be consistent with other card instances. Thx

**Comment by fuhton** [comment]
Merged. @jdrf-digitaldesigner Please confirm.

**Comment by jdrf-digitaldesigner** [comment]
Confirmed. Thx!
