### ISSUE TITLE
Font Size Variables

### ISSUE THREAD

**Issue by pmmck** [JDRF/design-system#166]
```
$font-size-lg: 0.875rem; /* 14px */
$font-size-sm: 0.8125rem; /* 13px */
```

- Does `*-lg` stand for "Large"?  If so, shouldn't the large be greater than 1rem?
- Is there a $font-size-base?

**Comment by RachelRVasquez** [comment]
@pmmck 

The base size is Bootstrap's default at 16px. The `*-lg` does stand for large. The Zeplin button designs  for large buttons have the font-size at 14px which is smaller than the base of 16. 1rem will be the base of 16.

**Comment by pmmck** [comment]
@RachelRVasquez if this variable is specific to buttons, shouldn't it be `.btn-font-size-lg`?

**Comment by RachelRVasquez** [comment]
@pmmck Naming conventions were based on Bootstrap's existing naming conventions. So if Bootstrap already had a variable `$font-size`, and we needed to expand on that, to prevent confusion, we kept the name and tacked on something of our own appended to it. This way we can still tell from a glance what we're overwriting while at the same time creating new variables related to the original variable.

Here's the Bootstrap V4 variables file for reference: https://github.com/twbs/bootstrap/blob/v4-dev/scss/_variables.scss

**Comment by pmmck** [comment]
@RachelRVasquez But 14px is not our large font size... If I wanted to _decrease_ the font size from our base of 16px I would use 14px.  To do so would mean I need to use a variable with the name large.  That doesn't make sense.

**Comment by fuhton** [comment]
@RachelRVasquez Let's add a clear comment in the variable file around our decision, implementation, and reasoning for using font-lg.

**Comment by RachelRVasquez** [comment]
@fuhton PR: https://github.com/JDRF/design-system/pull/237

**Comment by fuhton** [comment]
Merged. @pmmck Confirm?

**Comment by pmmck** [comment]
> The base size is Bootstrap's default at 16px. The *-lg does stand for large. The Zeplin button designs for large buttons have the font-size at 14px which is smaller than the base of 16. 1rem will be the base of 16.

I understand this logic if it were only used for buttons. But it's starting to be used in other places, like card:

```
.text-address {
    font-size: $font-size-lg;
    font-family: $font-medium;
    color: $text-muted;
```

Seeing that I would wonder why the text address is larger than 16px on cards.

I think the font size variables should be:

```
$font-size-base: 1rem; /* 16px */  
$font-size-sm: 0.875rem; /* 14px */ 
$font-size-lg: 1.125rem; /* 18px */ 
```

If the `-lg` is important for the buttons.scss, Bootstrap has a precedent for using component specific variations of the font size:

```
font-size: @jumbotron-font-size;
```

So we could have button specific variations:
```
$btn-font-size-lg: 0.875rem; /* 14px */ 
```
Although, our base button size also uses 14px font, so that isn't accurate either.

@RachelRVasquez @fuhton

**Comment by fuhton** [comment]
@RachelRVasquez CR submitted.

**Comment by RachelRVasquez** [comment]
@fuhton Merged. May have to push the compiled files on your end.
