### ISSUE TITLE
Button Colors

### ISSUE THREAD

**Issue by pmmck** [JDRF/design-system#168]
```
.btn {
		background-color: $jdrf-white;
		color: $jdrf-green;
		border-color: $jdrf-green;
```

Depending on the site's color theme, buttons could be blue, green, purple, orange, magenta.

Does it make sense to set the button colors in variables rather than declaring a specific color?

**Comment by RachelRVasquez** [comment]
@pmmck @fuhton To clarify, are you asking if we can create different classes that can be applied aside from the standard `.btn` so the colors can be changed?

**Comment by pmmck** [comment]
@RachelRVasquez different JDRF sites use different button colors.   For example, the JDRF One Walk website uses orange buttons.  The Ride website uses green buttons.

How can we setup our css so that a developer can easily set the:

- Button color
- Outline and Link button color

cc @fuhton

**Comment by fuhton** [comment]
Let's update the documentation to include that 3-6 lines of CSS are required to modify interactive colors.

Let's provide a clear example of this in use and suggest that the user add the CSS block immediately after the DS inclusion in the head. It needs to be included in the following pages and directly spell out how to use it.

* Downloads
* Buttons
* Colors

**Comment by RachelRVasquez** [comment]
@fuhton PRs:

https://github.com/JDRF/design-system/pull/217

https://github.com/JDRF/design-system/pull/218

**Comment by fuhton** [comment]
Merged. @pmmck Please review.

**Comment by pmmck** [comment]
@fuhton this works.  I have some tweaks to the copy which I will do via a Pull Request.
