### ISSUE TITLE
Section ".f-example" border width (very low priority)

### ISSUE THREAD

**Issue by McCallumDillon** [JDRF/design-system#17]
This is a super nit picky one.... (sorry)

To better reflect and emulate what we see in Zeplin lets change that 3px border on ".f-section .f-example" to 2px.  Zeplin actually shows "1px solid rgba(0, 0, 0, 0.12)" for that border, but this 'stands out' too much from the ' language-markup' below – so in retaining our #f7f7f7 color the 2px gets our border just a tad thinner for that modern / clean look we see in the Zeplin examples.

**Comment by RachelRVasquez** [comment]
@fuhton 
Change has been made to this PR: https://github.com/JDRF/design-system/pull/21

**Comment by fuhton** [comment]
Merged.

**Comment by RachelRVasquez** [comment]
@fuhton 

Created a PR with this separate change:

https://github.com/JDRF/design-system/pull/26

**Comment by fuhton** [comment]
Merged and confirmed.
