### ISSUE TITLE
Card Text Muted Variable

### ISSUE THREAD

**Issue by pmmck** [JDRF/design-system#172]
```
/* Cards */
$card-spacer-y: 0.625rem;
$card-spacer-x: 1.5rem;
$text-muted: $text-secondary;
$card-header-font-size: 1rem;
```

Is the `$text-muted` specific to the cards?  Or the entire DS?

**Comment by RachelRVasquez** [comment]
I'm not sure if we're still using this variable? I started removing it in some areas where the color could just be applied to the element as far as the cards go to prevent too many classes for a global style. E.g. `.ds-card-header`.  Thoughts @briansaycocie?

**Comment by pmmck** [comment]
@RachelRVasquez we will definitely want a muted class that we can apply to text elements.  Promotions That Give Back is a good example.  Where we have a special case for one of the card's headers to be a subtle note.  A muted class would eliminate the need for a variation in the cards css.   

@briansaycocie

**Comment by fuhton** [comment]
Merged. @jdrf-digitaldesigner @pmmck Please review.

**Comment by pmmck** [comment]
@fuhton I see the change where `.text-muted` has been added but i'm still seeing this variable grouped with the Card variables, even thought it's not specific to that component.

**Comment by RachelRVasquez** [comment]
@fuhton PR: https://github.com/JDRF/design-system/pull/239

**Comment by fuhton** [comment]
@pmmck This has been merged. Please review.

**Comment by pmmck** [comment]
Perfect, thanks.
