### ISSUE TITLE
Add button border variable for large buttons

### ISSUE THREAD

**Issue by pmmck** [JDRF/design-system#175]
After spending some more time with this, I've realized we need two border sizes.

```
$input-btn-border-width: 1px; // for small and regular buttons
$input-btn-border-width-lg: 2px; // for large buttons
```
 
cc @jdrf-digitaldesigner

**Comment by fuhton** [comment]
@pmmck Where would the larger border be applied? Just the large buttons?

**Comment by pmmck** [comment]
@fuhton only to large outline buttons.  So outline buttons by default, and at small sizes, have a 1px border.  But when we use the large outline buttons it's mostly for a Call To Action situation and so the 2px border is more appropriate.

**Comment by RachelRVasquez** [comment]
@fuhton 

PR submitted: https://github.com/JDRF/design-system/pull/185

**Comment by fuhton** [comment]
Merged. @pmmck @jdrf-digitaldesigner Please confirm.

**Comment by pmmck** [comment]
LGTM.
