### ISSUE TITLE
Strong Text font family

### ISSUE THREAD

**Issue by pmmck** [JDRF/design-system#176]
```
b,
strong {
	font-family: $font-bold;
```

Please change to `$font-medium'

**Comment by RachelRVasquez** [comment]
@pmmck Reviewed the Zeplin files and noticed Gotham Bold is specified in the Typography section. So far though, it doesn't appear that we use this font family. Are there cases where this font family comes into play or should it be removed?

cc: @fuhton

**Comment by pmmck** [comment]
@RachelRVasquez there is a good chance we will soon.  Let's keep it in there for now.  Thanks!

**Comment by RachelRVasquez** [comment]
@fuhton PR submitted: https://github.com/JDRF/design-system/pull/186

**Comment by fuhton** [comment]
Merged. @pmmck @jdrf-digitaldesigner Please confirm.

**Comment by pmmck** [comment]
LGTM.
