### ISSUE TITLE
Cards are not using the elevation mixins

### ISSUE THREAD

**Issue by pmmck** [JDRF/design-system#177]
```
.card {
	border-radius: 0 0 $border-radius $border-radius;
	box-shadow: 0 2px 2px 0 rgba(0, 0, 0, 0.12), 0 0 2px 0 rgba(0, 0, 0, 0.2);
}
```

**Comment by RachelRVasquez** [comment]
@briansaycocie This should be resolved once this ticket's PRs get approved. There was only one area I found in the cards that needed the mixin.

https://github.com/JDRF/design-system/issues/163

**Comment by briansaycocie** [comment]
:excellent: thanks @RachelRVasquez!

**Comment by briansaycocie** [comment]
@jdrf-digitaldesigner please confirm.

**Comment by pmmck** [comment]
LGTM thanks!
