### ISSUE TITLE
Five or 5?

### ISSUE THREAD

**Issue by pmmck** [JDRF/design-system#179]
We use `$grey-5` and `$elevation-five`

Should we stick with numbers or words?

**Comment by fuhton** [comment]
@RachelRVasquez I'm partial to numbers, basically because of bootstrap's conventions ( col-12 ).

Thoughts?

**Comment by RachelRVasquez** [comment]
@pmmck @fuhton Agreed. Let's swap for numbers. Will update the code as well as documentation/examples to reflect the change.

**Comment by RachelRVasquez** [comment]
@pmmck @fuhton Are we just re-naming variables or class names too? Like the elevation classes?

http://jdrf.github.io/design-system/dist/layout.html#elevation

**Comment by fuhton** [comment]
@RachelRVasquez Is this the only place we're spelling numbers out for class names?

**Comment by RachelRVasquez** [comment]
@fuhton To my knowledge from reviewing the io site, yep, it looks like everything else uses numbers including the Display typography classes.

**Comment by fuhton** [comment]
@RachelRVasquez Awesome. Yes - let's change class and variable names to use the numeric representations of numbers.

**Comment by RachelRVasquez** [comment]
@fuhton Submitted two PRs:

https://github.com/JDRF/design-system/pull/191

https://github.com/JDRF/design-system/pull/192

**Comment by fuhton** [comment]
Merged! @pmmck @jdrf-digitaldesigner Please confirm.

**Comment by pmmck** [comment]
LGTM!
