### ISSUE TITLE
Buttons: Toggle Icon Bar & Radio Buttons are seen in Zeplin but missing from our github?

### ISSUE THREAD

**Issue by McCallumDillon** [JDRF/design-system#18]
As the title says it- in Zeplin we have "Toggle Icon Bar & Radio Buttons" listed as examples of which I don't see on our Github page? Is this intended or stuff we need to add?

**Comment by fuhton** [comment]
These needed to be added. An oversight since they were added late.

**Comment by RachelRVasquez** [comment]
This task is in progress.

**Comment by RachelRVasquez** [comment]
@fuhton Status update on this: Everything's mostly done on my end but we may need to hook up Bootstrap's JS for the toggle states. We can discuss Tuesday after the holiday. I'm also not sure how we want to approach the checkbox/radio button designs versus how they are by default. Here's how they are in Bootstrap: http://v4-alpha.getbootstrap.com/components/buttons/

Was thinking maybe swapping material icons depending on if the form element was selected? Circle/Square for non selected button and then checkbox for selected. Thoughts? 

Once I get those styles figured out and the JS, then I'll push my commits for PR. Thanks.

**Comment by RachelRVasquez** [comment]
@fuhton 
Just submitted two PRs, one for master and one for gh-pages with only these changes.

https://github.com/JDRF/design-system/pull/22

https://github.com/JDRF/design-system/pull/23

**Comment by fuhton** [comment]
Merged #23 Had a question on #22

**Comment by RachelRVasquez** [comment]
@fuhton Noticing the vertical example includes dropdown buttons. Are we supporting those at this point in DS?

http://v4-alpha.getbootstrap.com/components/button-group/#vertical-variation

http://v4-alpha.getbootstrap.com/components/button-dropdown/

**Comment by fuhton** [comment]
No we aren't. Not yet.

**Comment by RachelRVasquez** [comment]
Ok will remove the dropdown from my examples then.

**Comment by RachelRVasquez** [comment]
Removed dropdown example. Vertical button groups added with tests and html. Here are the PRs that need approval.

https://github.com/JDRF/design-system/pull/27

https://github.com/JDRF/design-system/pull/22

**Comment by fuhton** [comment]
@RachelRVasquez Looks like all the CSS is working, but it's not retaining any click states? Is this because the JS isn't being included?

**Comment by RachelRVasquez** [comment]
@fuhton Yep - the JS adds the active class to the radio/checkbox buttons. The regular button groups don't appear to have JS to do this but I added the "active" class there for visual reference.

http://v4-alpha.getbootstrap.com/components/buttons/#checkbox-and-radio-buttons

**Comment by fuhton** [comment]
I'll take this over to add the JS.

**Comment by fuhton** [comment]
Closing this since the components have been added. Will open a new ticket to add in the JS.
