### ISSUE TITLE
Design System - Badges - ds-label ds-label-outline

### ISSUE THREAD

**Issue by jdrf-digitaldesigner** [JDRF/design-system#187]
Update L, R Padding: 8px, T, B Padding: 4px

Update font-weight: Medium

Update color to Hex value

Thx,

Ismael

**Comment by fuhton** [comment]
@RachelRVasquez PR Submitted.

**Comment by RachelRVasquez** [comment]
@fuhton Commented on PR #250

**Comment by fuhton** [comment]
@jdrf-digitaldesigner This is ready for review.

**Comment by jdrf-digitaldesigner** [comment]
Confirmed. Thx!
