### ISSUE TITLE
Design System - Badges - ds-label ds-label-default

### ISSUE THREAD

**Issue by jdrf-digitaldesigner** [JDRF/design-system#188]
Update title to "Solid"

Update font-weight: Medium

Update bacground-color: #9E9E9E

Thx,

Ismael

**Comment by fuhton** [comment]
@RachelRVasquez PR submitted.

**Comment by RachelRVasquez** [comment]
@fuhton Looked over PR #251 - looks like all the above issues are taken care of. Merged.

**Comment by fuhton** [comment]
@jdrf-digitaldesigner This is ready for review.

**Comment by jdrf-digitaldesigner** [comment]
Confirmed. Thx!
