### ISSUE TITLE
Remove outline from buttons :focus

### ISSUE THREAD

**Issue by pmmck** [JDRF/design-system#189]
![screen shot 2016-06-15 at 4 42 44 pm](https://cloud.githubusercontent.com/assets/385391/16096767/72febce4-3318-11e6-9c3b-f31680558a16.png)

**Comment by RachelRVasquez** [comment]
@fuhton PR submitted: https://github.com/JDRF/design-system/pull/193

**Comment by fuhton** [comment]
Merged. @pmmck @jdrf-digitaldesigner Please review.

**Comment by pmmck** [comment]
LGTM.
