### ISSUE TITLE
 language-markup to include variable conventions?

### ISSUE THREAD

**Issue by McCallumDillon** [JDRF/design-system#19]
Looking threw some key components such as the "color" and "typography" sections I see things like suggested font-family example to be " font-family: "Gotham Light"; "   or   in the color section we show #hex values for colors.  

Question: Should we include the recommend usage of $variables in that language markup instead or as well -- i.e.  "font-family: $font-light"   and   "color: $brand-primary" ?

**Comment by fuhton** [comment]
@RachelRVasquez Let's discuss this and move forward with this suggestion.

**Comment by RachelRVasquez** [comment]
@fuhton Submitted PR for this change:

https://github.com/JDRF/design-system/pull/30

**Comment by fuhton** [comment]
Merged and looks correct.
