### ISSUE TITLE
Consider utilizing SVG sprites instead of icon fonts.

### ISSUE THREAD

**Issue by magnificode** [JDRF/design-system#2]
I think we could benefit a bit from a performance standpoint if instead of utilizing icon-fonts for buttons with icons next to them. Currently it looks like there's only a couple button variations, and a full HTTP request for a new font may be a bit excessive if we can utilize an SVG sprite.

If however we are only planning on ever using the Google Material Icons next to buttons, it's entirely possible that the font is already cached, but this does limit us if in the future the client would like some sort of custom iconography.

**Comment by fuhton** [comment]
Since the expectation is that we will always be using Material Icons, I'm comfortable leaving the current implementation as is. In the future if we ever add in custom iconography, we'd definitely want to include them as SVG sprites to reduce load times and allow immediate access.
