### ISSUE TITLE
Flat elevation breaking the inline elevation samples

### ISSUE THREAD

**Issue by RachelRVasquez** [JDRF/design-system#204]
It looks like the elevations are no longer inline with the addition of "flat".

http://jdrf.github.io/design-system/dist/layout.html#elevation

![screen shot 2016-06-16 at 8 36 37 am](https://cloud.githubusercontent.com/assets/10246844/16116947/8c72ca14-339d-11e6-8f9d-2d9352fd53c2.png)

**Comment by RachelRVasquez** [comment]
@fuhton This has been resolved in this issue/PR:

https://github.com/JDRF/design-system/issues/163

**Comment by fuhton** [comment]
I still see this as an issue.

**Comment by RachelRVasquez** [comment]
@fuhton Both PRs on #163 have not been merged yet to resolve this issue.
