### ISSUE TITLE
Dark Colors

### ISSUE THREAD

**Issue by fuhton** [JDRF/design-system#208]
In Zeplin, Text and outline buttons require a darker variation of the button colors. It'd be great to include this programmatically using SASS's built-in mixin darken(); 

These only affect outline buttons.

**Comment by RachelRVasquez** [comment]
@fuhton PR: https://github.com/JDRF/design-system/pull/213

**Comment by RachelRVasquez** [comment]
@fuhton PRs:

https://github.com/JDRF/design-system/pull/223

https://github.com/JDRF/design-system/pull/224

**Comment by fuhton** [comment]
Merged. @pmmck Confirm?

**Comment by pmmck** [comment]
@fuhton I'm fine with closing out this Issue.  However, color in the DS is going to require some more thought and conversation.  Ismael and I are discussing what the default button color should be, what the rules are in applying that color across different sites and how color is used in things like card titles, navigation, text links, etc.   Expect more work on Color in the backlog soon.  Thanks!

cc @jdrf-digitaldesigner
