### ISSUE TITLE
Design System - Badges - Sizes

### ISSUE THREAD

**Issue by jdrf-digitaldesigner** [JDRF/design-system#212]
Update all Badges Padding: L, R: 8px, T, B: 4px

Update all H3 Titles "Heading Three" Line Height: 32px

Update all H1 and H2 Badges font-weight: Book, and others to font-weight: Medium

*Solid Badges - Update background-color: #9e9e9e

Thx,

Ismael

**Comment by fuhton** [comment]
@RachelRVasquez PR Submitted.

**Comment by RachelRVasquez** [comment]
@fuhton Woops thought this was an issue for me. Disregard this PR: https://github.com/JDRF/design-system/pull/252

**Comment by RachelRVasquez** [comment]
@fuhton Commented on PRs.

**Comment by RachelRVasquez** [comment]
@fuhton Merged.

**Comment by fuhton** [comment]
@jdrf-digitaldesigner This is ready for review.

**Comment by jdrf-digitaldesigner** [comment]
Confirmed. Thx!
