### ISSUE TITLE
Design System - Badges - Variations

### ISSUE THREAD

**Issue by jdrf-digitaldesigner** [JDRF/design-system#216]
Update Badge Padding: L, R: 8px, T, B: 4px

Update Badge font-weight: medium

Center Button Labels and Badges vertically

Add white border to Outline Button Hover state

Remove bottom row (see attachment) 
![screen shot 2016-06-16 at 11 51 42 am](https://cloud.githubusercontent.com/assets/19931482/16123400/c8c0b524-33b8-11e6-92e0-bb22f6fb0b82.png)

Thx,

Ismael

**Comment by fuhton** [comment]
@RachelRVasquez PR submitted.

**Comment by RachelRVasquez** [comment]
@fuhton Merged.

**Comment by fuhton** [comment]
@jdrf-digitaldesigner This is ready for review.

**Comment by jdrf-digitaldesigner** [comment]
Looks good, but can we please disregard my previous comment "Add white border to Outline Button Hover state" and revert to not having a stroke on Outline Button Hover state? Sorry about the confusion. Thx

**Comment by fuhton** [comment]
Merged. @jdrf-digitaldesigner Please confirm.

**Comment by jdrf-digitaldesigner** [comment]
Confirmed. Thx!
