### ISSUE TITLE
Change padding to 16px on .ds-card-content for header/content

### ISSUE THREAD

**Issue by RachelRVasquez** [JDRF/design-system#225]
Match padding to Zeplin for content card (details card).

**Comment by RachelRVasquez** [comment]
@fuhton PRs:

https://github.com/JDRF/design-system/pull/227

https://github.com/JDRF/design-system/pull/228

**Comment by fuhton** [comment]
Merged. @pmmck Confirm?

**Comment by jdrf-digitaldesigner** [comment]
Top and Bottom Padding is still showing as 10px on the following Cards:

phantom-ds-card-content-header-footer

phantom-ds-card-content-header

Thx,

Ismael

**Comment by fuhton** [comment]
@jdrf-digitaldesigner What should the padding be?

**Comment by jdrf-digitaldesigner** [comment]
16px

**Comment by fuhton** [comment]
Merged. @jdrf-digitaldesigner @pmmck Please review.

**Comment by jdrf-digitaldesigner** [comment]
Confirmed. Thx!
