### ISSUE TITLE
Mobile menu won't open

### ISSUE THREAD

**Issue by pmmck** [JDRF/design-system#240]
Tapping "menu" icon in the header doesn't open a menu.

**Comment by fuhton** [comment]
@pmmck I'm finding this as working.

**Comment by pmmck** [comment]
@fuhton you are correct, it is working on native mobile devices.  I tested both iOS and Android.  It seems to only be an issue on desktop with small viewport sizes.   Both Chrome and FF on OSX.

**Comment by fuhton** [comment]
@pmmck If you resize and **then** refresh the page is it working?

**Comment by pmmck** [comment]
@fuhton yep!
