### ISSUE TITLE
Badges font alignment

### ISSUE THREAD

**Issue by fuhton** [JDRF/design-system#257]
I want to confirm that line-height is correct for all badges.

In Zeplin the font of the badge is not on the same line as the font of the containing element, but it seems to be that way in the implementation. I want to confirm this as correct?

<img width="565" alt="image 2016-06-20 at 2 12 58 pm" src="https://cloud.githubusercontent.com/assets/1857806/16205371/7efa99e6-36f1-11e6-9716-482e3596da01.png">

**Comment by jdrf-digitaldesigner** [comment]
The Badges in Zeplin were vertically aligned to the Label's Text Box, based on line height. I don't see it as an issue. @pmmck, your call. Thx

**Comment by pmmck** [comment]
@fuhton @jdrf-digitaldesigner in Zeplin the badges are vertically centered within the line-height.  In the implementation, they are aligned to the baseline.  This looks fine at some sizes but not others. 

![screen shot 2016-06-21 at 9 15 26 am](https://cloud.githubusercontent.com/assets/385391/16230674/b94428de-3790-11e6-9896-8c8c548c7c2e.png)

For the badges inside buttons, a -1px margin has been applied to help with alignment.  I'm not sure if that has been applied with adjustments to all the various button sizes.

**Comment by RachelRVasquez** [comment]
@pmmck @jdrf-digitaldesigner 

To clarify, the issue we're discussing is that the text inside the labels/badges aren't always on the same baseline as the content outside of it to the left?

So we want to ensure it's always on the baseline regardless of size? Is there an example where we're not seeing it line up? Here's a screenshot of the demo site:

![screen shot 2016-06-23 at 1 22 44 pm](https://cloud.githubusercontent.com/assets/10246844/16313136/ef7fddf6-3945-11e6-943d-e1fe554292e6.png)

cc: @fuhton

**Comment by pmmck** [comment]
@RachelRVasquez My eyes are playing tricks on me.  You are correct!  Thanks.
