### ISSUE TITLE
Add box shadow to image cap cards (image)

### ISSUE THREAD

**Issue by RachelRVasquez** [JDRF/design-system#258]
Missing box shadow beneath the image for image cap cards from designs:

http://jdrf.github.io/design-system/dist/components.html#cards

![screen shot 2016-06-20 at 3 35 21 pm](https://cloud.githubusercontent.com/assets/10246844/16207733/be149400-36fc-11e6-8c26-9313ba185d41.png)

**Comment by RachelRVasquez** [comment]
@fuhton PR submitted: https://github.com/JDRF/design-system/pull/259

**Comment by fuhton** [comment]
Merged.
