### ISSUE TITLE
Re-structure Feature Card w/ Momentum Line for IE support

### ISSUE THREAD

**Issue by RachelRVasquez** [JDRF/design-system#260]
Re-structure this card so the image can reach 100% based on the content even without `object-fit` in IE where it's not supported.

**Comment by RachelRVasquez** [comment]
@fuhton PRs submitted:

https://github.com/JDRF/design-system/pull/261

https://github.com/JDRF/design-system/pull/262

**Comment by fuhton** [comment]
Merged
