### ISSUE TITLE
Padding adjustments to Momentum Line Feature Card

### ISSUE THREAD

**Issue by RachelRVasquez** [JDRF/design-system#265]
Match paddings to Zeplin design so we can remove these styles in Promotions.

- In Promotions: Removed the padding bottom on .ds-card-block due to the padding bottom that comes from the WP text editor's P tags to match Zeplin.
- In Promotions: Changed the padding on .ds-card-header to 1rem top/bottom (16px) to match Zeplin.
- In Promotions: Changed the margin bottom of .ds-card-title to .5rem (8px) to match Zeplin.
- In Promotions: Changed padding-top of .ds-card-block to 1rem on mobile - this needs to be corrected on the DS.

**Comment by RachelRVasquez** [comment]
@fuhton PRs submitted:

https://github.com/JDRF/design-system/pull/266

https://github.com/JDRF/design-system/pull/267

I notice we don't account for social icons on the DS when compared to the Zeplin designs - how are we handling the padding that's usually applied via the icon area on mobile? Right now without those icons, the card appears like this on mobile with the changes (below the Details button):

![screen shot 2016-06-24 at 2 08 20 pm](https://cloud.githubusercontent.com/assets/10246844/16346461/7be5d474-3a15-11e6-80a8-9f48a9560705.png)

**Comment by fuhton** [comment]
Merged

**Comment by RachelRVasquez** [comment]
Forgot a margin-bottom change to `ds-card-subtitle`.

Will submit another PR for it.

**Comment by RachelRVasquez** [comment]
@fuhton 

PR for margin on subtitle for this card only:

https://github.com/JDRF/design-system/pull/268

**Comment by fuhton** [comment]
Merged.
