### ISSUE TITLE
H3 Code Update

### ISSUE THREAD

**Issue by jdrf-digitaldesigner** [JDRF/design-system#269]
Please update the H3 line-height property to 28px, to match the documentation. Thx

**Comment by RachelRVasquez** [comment]
@jdrf-digitaldesigner It appears the H3 lineheight conforms the to the Zeplin design at 20px/24px for default and 24px/28px for breakpoints above "small". Can you confirm whether we're following the Zeplin designs and fixing the typo in the git documentation, or are we changing the line height from the original design?

cc: @fuhton

**Comment by jdrf-digitaldesigner** [comment]
@RachelRVasquez We're actually sticking to what's in the Git documentation (line-height: 28px) and disregarding the Zeplin file, in this instance.

**Comment by fuhton** [comment]
@pmmck This is ready for your review.

**Comment by fuhton** [comment]
@pmmck @jdrf-digitaldesigner Have either of you had a chance to review this ticket?

**Comment by jdrf-digitaldesigner** [comment]
@pmmck Looks good on my end.
