### ISSUE TITLE
Rename _type.scss to _typography.scss

### ISSUE THREAD

**Issue by magnificode** [JDRF/design-system#3]
Just so that it matches the title of the section it references.

**Comment by RachelRVasquez** [comment]
The files are named after their Bootstrap V4 counterparts that we're overwriting so we can easily reference them in the future. While changing the name from _type to _typography is a small change, I'd like to keep the structure/naming matching Bootstrap's so we can visually see the relationship between the two during the overwriting process.

The only files that don't follow this naming convention are files of our own creation that don't have matches in Bootstrap - like the the elevations.

**Comment by magnificode** [comment]
Makes total sense 👍  thanks!
