### ISSUE TITLE
Getting Started Documentation

### ISSUE THREAD

**Issue by RachelRVasquez** [JDRF/design-system#314]
http://jdrf.github.io/design-system/dist/getting-started.html

There is some repetition in the "Fonts" section and the `@fontface` CSS to get the fonts working hasn't been documented.

> If font files are needed for the website/application, copy/download the font files found in the master branch. It's recommended to place the font folder in a similar path to the CSS files.

It also looks like the "Javascript" section was either cut off (says "using javascript") or it needs content.

**Comment by fuhton** [comment]
Merged.
