### ISSUE TITLE
Address Form/Type

### ISSUE THREAD

**Issue by RachelRVasquez** [JDRF/design-system#315]
There is no "address" type for inputs within the Address form sections. The "address" types can be changed to "text".

DS: http://jdrf.github.io/design-system/dist/components.html#forms

HTML Reference: http://html5doctor.com/html5-forms-input-types/

![screen shot 2016-07-21 at 11 22 20 am](https://cloud.githubusercontent.com/assets/10246844/17028407/7efcf6da-4f35-11e6-9ec8-11c0ba61a3b8.png)

**Comment by fuhton** [comment]
@RachelRVasquez CR Approved and merged.

**Comment by fuhton** [comment]
@pmmck This is ready for your review.

**Comment by pmmck** [comment]
@fuhton what specifically am I looking for here?

**Comment by fuhton** [comment]
@pmmck Didn't realize this was an internal tweak. We've modified an input type in the github page.
