### ISSUE TITLE
Images should have a border radius of 0.

### ISSUE THREAD

**Issue by pmmck** [JDRF/design-system#321]
The image in the card with the Title and Subtitle has a 2px border radius. 

![rounded corner on images](https://cloud.githubusercontent.com/assets/385391/17297058/028e259c-57d2-11e6-8d5d-6ad118a488a4.png)

**Comment by RachelRVasquez** [comment]
@pmmck Does this change only apply to this specific card or all cards that have "image caps" when they're on top?
![screen shot 2016-08-03 at 9 42 13 am](https://cloud.githubusercontent.com/assets/10246844/17367595/9788a496-595e-11e6-878d-e165772449f9.png)

**Comment by pmmck** [comment]
@RachelRVasquez the top of the cards should always have a 2px border radius.  We do not want this to impact the appearance of the top of the card.

**Comment by fuhton** [comment]
@pmmck This is ready for your review.

**Comment by pmmck** [comment]
@fuhton this looks good to me.  Should I assign stuff back to you or just close out?

**Comment by fuhton** [comment]
@pmmck Feel free to close it out!
