### ISSUE TITLE
Add font smoothing to improve the legibility of text

### ISSUE THREAD

**Issue by pmmck** [JDRF/design-system#322]
-webkit-font-smoothing: antialiased;
-moz-osx-font-smoothing: grayscale;

![font smoothing](https://cloud.githubusercontent.com/assets/385391/17298143/bcebc698-57d6-11e6-8da1-b11c12e7fbd9.png)

**Comment by fuhton** [comment]
@RachelRVasquez CR Approved and merged.

**Comment by fuhton** [comment]
@pmmck This is ready for your review.

**Comment by pmmck** [comment]
@fuhton this looks good.  It now needs to be applied to Promotions: https://trello.com/c/JbLmydV0

**Comment by fuhton** [comment]
@pmmck As we make adjustments, this will be included. If it's working as expected for this product, let's close the ticket.

**Comment by pmmck** [comment]
@fuhton looks good.
