### ISSUE TITLE
Program Card - Possible style adjustments needed

### ISSUE THREAD

**Issue by briansaycocie** [JDRF/design-system#338]
Hi @pmmck,

After reviewing the [Event Calendar mobile comps](https://app.zeplin.io/project.html#pid=55a514081c757ce422fceb60&sid=57aa430c829374a67ff97b52), I noticed a styling difference with the DS Program Card from the way it was originally built. 

From the [Cards comp on Zeplin](https://app.zeplin.io/project.html#pid=55a514081c757ce422fceb60&sid=57508e86c15ddea54f4407b4), the card was built using two columns that scale down to a smaller version of it on mobile. Keeping the columns intact means the content in the left column gets a bit of a squeeze:
![screenshot 2016-08-22 11 20 30](https://cloud.githubusercontent.com/assets/1328262/17862465/f06eeaa6-685a-11e6-9547-f5f4fadbdd34.png)

The Event Calendar mobile comps display the title and location the full width of the card, which makes a lot of sense:
![screenshot 2016-08-22 11 19 37](https://cloud.githubusercontent.com/assets/1328262/17862531/4ddb5c6a-685b-11e6-9df6-870bde5ae4b6.png)

I wanted to get your thoughts on how you would like to proceed.

**Comment by pmmck** [comment]
Hi @briansaycocie — the cards in Zeplin are correct.  Thanks!

**Comment by briansaycocie** [comment]
Great thanks for the clarification. Closing out.
