### ISSUE TITLE
Add note about heading classes

### ISSUE THREAD

**Issue by RachelRVasquez** [JDRF/design-system#34]
Add note about heading classes in use for Typography where headings are.

http://jdrf.github.io/design-system/dist/content.html#typography

**Comment by RachelRVasquez** [comment]
Created a PR: https://github.com/JDRF/design-system/pull/38 

Looks like it counts me not committing compiled files as changes?

**Comment by fuhton** [comment]
Compiled files were included in this PR. It was declined. Please re-submit without the compiled files.

**Comment by RachelRVasquez** [comment]
Just re-submitted a new PR without any compiled files:

https://github.com/JDRF/design-system/pull/61
