### ISSUE TITLE
Forms - Field labels: Update font size to 15px

### ISSUE THREAD

**Issue by jdrf-digitaldesigner** [JDRF/design-system#340]
![screen shot 2016-08-29 at 3 15 03 pm](https://cloud.githubusercontent.com/assets/19931482/18063993/6587a26a-6dfb-11e6-8373-0e61c6fd6a03.png)

**Comment by pmmck** [comment]
This is an iteration from the initial design.

**Comment by RachelRVasquez** [comment]
Created a duplicate in Trello and will continue progress/conversation there.
