### ISSUE TITLE
Forms - Horizontal Checkboxes: Update spacing to 24px between options

### ISSUE THREAD

**Issue by jdrf-digitaldesigner** [JDRF/design-system#342]
![screen shot 2016-08-29 at 3 20 55 pm](https://cloud.githubusercontent.com/assets/19931482/18064172/35f431e8-6dfc-11e6-9e3b-d3b93af15f00.png)

**Comment by RachelRVasquez** [comment]
Created a duplicate in Trello. Will continue progress/conversation there.
