### ISSUE TITLE
Forms - Success and Error icons: Update size to 24px

### ISSUE THREAD

**Issue by jdrf-digitaldesigner** [JDRF/design-system#344]
![screen shot 2016-08-29 at 3 25 19 pm](https://cloud.githubusercontent.com/assets/19931482/18064306/d0fc2eca-6dfc-11e6-8897-12dcb03d94bd.png)

**Comment by RachelRVasquez** [comment]
I've created a Trello ticket instead for this issue and will be continuing work/conversation there. Thanks!
