### ISSUE TITLE
Forms - IE9: Disabled fields allow users to enter values

### ISSUE THREAD

**Issue by jdrf-digitaldesigner** [JDRF/design-system#345]
![screen shot 2016-08-29 at 4 41 20 pm](https://cloud.githubusercontent.com/assets/19931482/18066700/7f928bdc-6e07-11e6-88f5-92a1c70a079b.png)

**Comment by fuhton** [comment]
@RachelRVasquez Thoughts on this?

**Comment by RachelRVasquez** [comment]
@jdrf-digitaldesigner Can you provide a link to the issue on a page as well as how you're setting up the disabled field on the dashboard?

**Comment by jdrf-digitaldesigner** [comment]
Hey @RachelRVasquez, this was accomplished by adding the class in the code, which is possible in BrowserStack, so I'll close the issue. Thx
