### ISSUE TITLE
Forms - IE9 - Text Field & Hidden Labels: Hidden labels not showing

### ISSUE THREAD

**Issue by jdrf-digitaldesigner** [JDRF/design-system#346]
![screen shot 2016-08-29 at 4 42 48 pm](https://cloud.githubusercontent.com/assets/19931482/18066750/babe322e-6e07-11e6-8e30-fcef1720abd1.png)

**Comment by RachelRVasquez** [comment]
This works when applying the `.ds-sr-only` class to the label via the inspector. Salesforce currently does not offer the option to hide labels. Re-assigning to @fuhton for further feedback.
