### ISSUE TITLE
Forms - IE9 - Datefield: Form-control not showing

### ISSUE THREAD

**Issue by jdrf-digitaldesigner** [JDRF/design-system#349]
![screen shot 2016-08-29 at 4 46 34 pm](https://cloud.githubusercontent.com/assets/19931482/18066852/2c11460a-6e08-11e6-872b-a051d17a561d.png)

**Comment by RachelRVasquez** [comment]
The date format seen in Chrome is not supported in all browsers:

http://v4-alpha.getbootstrap.com/components/forms/#textual-inputs

Instead we can use the "description" field to fill in any preferred formats. Thoughts @fuhton?

Screenshots of Chrome VS Safari when using the description field on the dashboard from the forms.

Chrome:
![screen shot 2016-09-02 at 11 42 19 am](https://cloud.githubusercontent.com/assets/10246844/18209600/6ee68574-7102-11e6-9932-d21ac6d1b065.png)

Safari:
<img width="547" alt="screen shot 2016-09-02 at 11 42 38 am" src="https://cloud.githubusercontent.com/assets/10246844/18209601/6ee97d9c-7102-11e6-91d6-cc1c1dae8325.png">
