### ISSUE TITLE
Badge section doesn't correspond with side nav

### ISSUE THREAD

**Issue by pmmck** [JDRF/design-system#373]
The Badges section should move to the bottom of the Components view.

https://www.evernote.com/l/ABetFD_2UWBIRYCmw_blW7PmqiD7vfTl41s

**Comment by fuhton** [comment]
@RachelRVasquez This is #1

**Comment by RachelRVasquez** [comment]
@fuhton Submitted a PR: https://github.com/JDRF/design-system/pull/375

**Comment by fuhton** [comment]
Merged and pushed.
