### ISSUE TITLE
Custom selects' options are white on white on Windows

### ISSUE THREAD

**Issue by noahcooper** [JDRF/design-system#383]
In /src/scss/_custom-forms.scss, `.c-select` is set to `color: transparent`. This results in selects' options appearing to be white on white when opened. The option text is only visible when selected.

It looks like this only happens on Windows -- Mac seems to ignore the transparent color declaration.

**Comment by briansaycocie** [comment]
Thanks for finding that issue @noahcooper. I can confirm the issue exists in Chrome v54 - Windows 10.

I've just submitted a PR to resolve the issue. It appears the `color: transparent` _and_ `text-shadow: 0 0 0 #000` was added to resolve a specific Firefox issue displaying a focused dotted outline. I've moved those styles into a `:-moz-focusring` pseudo selector so it's only applied to Firefox.

Closing out.
