### ISSUE TITLE
Bootstrap v4's Labels component no longer exists

### ISSUE THREAD

**Issue by briansaycocie** [JDRF/design-system#385]
When the [DS Badge's component](https://jdrf.github.io/design-system/dist/components.html#05-badges) was built, it was based on [Bootstrap v4 Label's component](https://v4-alpha.getbootstrap.com/components/label/) which I come to find out, no longer exists as of `v4.0.0-alpha.3` (current implementation is based on `v4.0.0-alpha.2`). This component has been replaced with the [Tag's component](https://v4-alpha.getbootstrap.com/components/tag/) according to their [migration documentation](https://v4-alpha.getbootstrap.com/migration/).

Basically, this means new developers that set up Design Systems locally will have an issue compiling SASS as its importing the Labels SASS partial [@import 'scss/labels'](https://github.com/JDRF/design-system/blob/master/src/scss/_badges.scss#L1) from npm (which no longer exists if you do a recent `npm install` as I come to find out while troubleshooting a separate issue). My workaround for this was to get a copy of another developer's `node_modules` folder that has worked on this repo previously (got it from Nick) and replaced it with mine, which isn't ideal.

My recommendation: Rework the DS Badge's component to utilize the new Bootstrap v4 Tag's component.

**Comment by pmmck** [comment]
@briansaycocie thanks for catching this.  I've opened a ticket: https://trello.com/c/XRQkyjvn

**Comment by mrbobbybryant** [comment]
We have decided to lock in the current version of bootstrap so that future changes will not break existing features. Thanks @briansaycocie for pointing out this issue. 

This was fixed by the following pull request.
https://github.com/JDRF/design-system/pull/390
