### ISSUE TITLE
Fatal error after git clone and npm run pull

### ISSUE THREAD

**Issue by briansaycocie** [JDRF/design-system#41]
When I clone the repo and run `npm run pull`, I get a fatal error after gulp runs in the master branch.

To reproduce:
1. git clone git@github.com:JDRF/design-system.git
2. cd design-system
3. npm run pull

Screenshot:
![screenshot 2016-06-02 13 53 56](https://cloud.githubusercontent.com/assets/1328262/15757059/7aa3ecd4-28c9-11e6-9579-4d231f5cb240.png)

npm-debug.log:
![screenshot 2016-06-02 13 55 09](https://cloud.githubusercontent.com/assets/1328262/15757114/b37bf538-28c9-11e6-91f6-471f91a73bfb.png)

**Comment by fuhton** [comment]
@briansaycocie What's your version of Node and NPM?

**Comment by briansaycocie** [comment]
@fuhton node v5.5.0, npm v3.5.3

**Comment by fuhton** [comment]
I'd suggest updating node, npm, and global gulp to the latest version and retest.

**Comment by briansaycocie** [comment]
I've updated to node v6.2.0, npm v3.8.9, and gulp v3.9.1. Same result :(

**Comment by briansaycocie** [comment]
Figured out the issue. The latest version (v0.4.0) of gulp-scss-lint threw a fatal error but did not specific what the issue was. I reverted it back to v0.3.9 and ran `npm run pull`. It failed at the same spot, except this time I got a helpful error message: `Error: You need to have Ruby and scss-lint gem installed`.

Running `gem install ruby && gem install scss-lint` fixed it for me.
