### ISSUE TITLE
Broken link in Content > Colors

### ISSUE THREAD

**Issue by briansaycocie** [JDRF/design-system#44]
On the Content page, when I click on the "outline button style" link, I see the 404 Github page.

To reproduce:
1. Go to https://jdrf.github.io/design-system/dist/content.html
2. Scroll down to Button Colors
3. Click "outline button style"

![screenshot 2016-06-02 14 16 55](https://cloud.githubusercontent.com/assets/1328262/15757744/b8394bcc-28cc-11e6-88f3-79149ac03382.png)

**Comment by fuhton** [comment]
Merged and confirmed as fixed.
