### ISSUE TITLE
Broken link in Content > Icons

### ISSUE THREAD

**Issue by briansaycocie** [JDRF/design-system#46]
On the Content page, when I click on the "button classes" link, I see the 404 Github page.

To reproduce:
1. Go to https://jdrf.github.io/design-system/dist/content.html
2. Scroll down to Icons
3. Click "button classes"

![screenshot 2016-06-02 14 42 39](https://cloud.githubusercontent.com/assets/1328262/15758453/48d47794-28d0-11e6-8268-e645797a72a4.png)

**Comment by fuhton** [comment]
Merged and confirmed as fixed.
