### ISSUE TITLE
IE9 / Windows 7 (desktop) - Icon Only Buttons not quite centered

### ISSUE THREAD

**Issue by McCallumDillon** [JDRF/design-system#47]
![screen shot 2016-06-02 at 12 44 17 pm](https://cloud.githubusercontent.com/assets/5239235/15758524/ddac0c4e-28bf-11e6-8d4a-e377ecca28f4.jpg)

Screenshot shows the icon 'slightly' offeset

**Comment by McCallumDillon** [comment]
![screen shot 2016-06-02 at 1 12 03 pm](https://cloud.githubusercontent.com/assets/5239235/15759490/a8199caa-28c3-11e6-964d-6216222b5185.jpg)
we also see this here on the toggle icon bar

**Comment by RachelRVasquez** [comment]
Created a PR for the button icons:

https://github.com/JDRF/design-system/pull/68

**Comment by fuhton** [comment]
Merged and confirmed.
