### ISSUE TITLE
IE9 / Windows 7 (desktop):  Ripple effect isn't working on buttons

### ISSUE THREAD

**Issue by McCallumDillon** [JDRF/design-system#48]
IE9:  ![rec](https://cloud.githubusercontent.com/assets/5239235/15758714/bb2b288e-28c0-11e6-9820-4ad4eb628490.gif)

Clicking the button doesn't show the ripple effect.

Happens for both IE9  and  IE10 on Windows 7.

**Comment by fuhton** [comment]
This is resolved on IE 10. Issue is now more "broken" on IE9.

**Comment by fuhton** [comment]
Instead of supporting this in IE9, we'll be moving to excluding this from IE9 using JavaScript/jQeruy. I've created a new ticket for this #67
