### ISSUE TITLE
IE9 / Windows 7: Placeholder text does not display in search bar

### ISSUE THREAD

**Issue by briansaycocie** [JDRF/design-system#52]
In IE9, the placeholder text "Search..." does not display in the search bar.

![screenshot 2016-06-02 15 37 39](https://cloud.githubusercontent.com/assets/1328262/15760270/ffe98e9a-28d7-11e6-8574-b5d8387d77aa.png)

**Comment by fuhton** [comment]
Bootstrap explicitly says it does not support ie9 Placeholders - http://v4-alpha.getbootstrap.com/getting-started/browsers-devices/#internet-explorer-9
