### ISSUE TITLE
Missing checkbox and radio icons for associated buttons

### ISSUE THREAD

**Issue by briansaycocie** [JDRF/design-system#56]
On the Components page, the checkbox and radio buttons display text with no icons. On Zeplin, the icons are included with different states when clicked.

Components page:
![screenshot 2016-06-02 16 32 48](https://cloud.githubusercontent.com/assets/1328262/15761787/b6bb9d3c-28df-11e6-83b5-17297728a95b.png)

Zeplin:
![screenshot 2016-06-02 16 33 06](https://cloud.githubusercontent.com/assets/1328262/15761794/bea75af4-28df-11e6-96e3-8caf33590da7.png)

**Comment by fuhton** [comment]
Having checkbox and radio button form elements are out of the scope of this project. Having Radio Buttons ( btn ) and Checkbox Buttons ( btn ). We've followed closely to Zeplin's styling, but opted to implement Bootstrap's implementation.

http://v4-alpha.getbootstrap.com/components/buttons/#checkbox-and-radio-buttons

@pmmck

**Comment by pmmck** [comment]
Let's remove Radio and Checkbox buttons until we add form controls.

The "Toggle Segment" and "Toggle Icon Bar" is already using the Button Group HTML.  So how about we rename them to "Button Group" and "Button Toolbar"?

@briansaycocie @fuhton
