### ISSUE TITLE
IE9/10/11, Windows 7: Line break on the Gray 7 palette

### ISSUE THREAD

**Issue by briansaycocie** [JDRF/design-system#57]
On the Content page, the 7th and darkest grey (#757575) wraps down to the next row. The expected behavior is having that palette line up with the rest of the grey palettes.

Current:
![screenshot 2016-06-02 16 54 47](https://cloud.githubusercontent.com/assets/1328262/15762463/9664014c-28e3-11e6-9874-35e715b660c4.png)

Expected:
![screenshot 2016-06-02 16 55 00](https://cloud.githubusercontent.com/assets/1328262/15762467/9d26526e-28e3-11e6-9cf8-e982e8dc2202.png)

**Comment by fuhton** [comment]
This affects all browsers in some way. Noticed on Chrome at sub-976px this is pushing elements to the next line.

**Comment by fuhton** [comment]
@briansaycocie I think this is better than the alternative - http://cl.ly/342b2r0A030A

**Comment by briansaycocie** [comment]
That works for me. Closing out.
