### ISSUE TITLE
README instructions on gh-pages branch

### ISSUE THREAD

**Issue by RachelRVasquez** [JDRF/design-system#62]
https://github.com/JDRF/design-system/blob/gh-pages/README.md

The README on the gh-pages branch has instructions that are a bit misleading. It currently says:

> This will pull the latest code, run npm install, and afterwords run gulp.

And the code sample below is `npm run pull`.

I think we can change this to:

> In your current project folder (gh-pages) and the sub-folder (master), run `npm install` and then `gulp`.

With the code sample below being:

```
npm install
gulp
```

I'd like to clarify this content so the reader understands that once they have master set up as a sub-directory, they need to run these commands in both folders.

**Comment by fuhton** [comment]
Agreed. I think the language is not correct.
