### ISSUE TITLE
Issue with local dev setup in gh-pages branch

### ISSUE THREAD

**Issue by briansaycocie** [JDRF/design-system#64]
After running the initial setup with the correct file structure, I ran into an issue with `npm run pull` inside the gh-pages branch. I had the `npm run setup` fail on me with the error message `npm ERR! missing script: setup`.

I ran `npm run pull` inside the design-system sub folder (master branch), and that seemed to work. To resolve, I think the script will need to update from this:
```
npm install && cd design-system && npm run setup && cd .. && gulp
```
to
```
npm install && cd design-system && npm run pull && cd .. && gulp
```

**Comment by fuhton** [comment]
@briansaycocie I'm not able to find this in the documentation? I believe it's already been changed - can you confirm?

**Comment by briansaycocie** [comment]
@fuhton I think this is more an issue with the script than it is the documentation. It could be that `npm run setup` isn't working specifically on my machine. Not a critical issue as I'm able to still do work without running that command.

**Comment by fuhton** [comment]
@briansaycocie Have you updated your local to be inline with the current JDRF master/gh-pages branch?

**Comment by briansaycocie** [comment]
@fuhton Just synced the branches on my fork and ran `npm run pull` again. I get the same `npm ERR! missing script: setup` error.

![screenshot 2016-06-08 10 56 17](https://cloud.githubusercontent.com/assets/1328262/15901249/1cd3df6c-2d68-11e6-9828-b418826f5644.png)

**Comment by fuhton** [comment]
Odd. It's clear in the [code](https://github.com/JDRF/design-system/blob/gh-pages/package.json#L14) that it's `pull` not `setup`

**Comment by fuhton** [comment]
@briansaycocie Any thoughts?

**Comment by briansaycocie** [comment]
:doh: I synced the master branch but not gh-pages. Synced up and retested, it's now working for me. :) Closing out.
