### ISSUE TITLE
Make Ripple inclusive of all 'btn' classes

### ISSUE THREAD

**Issue by fuhton** [JDRF/design-system#66]
By default, in the Design System, we need to make the ripple effect trigger on all `btn` button classes. While this is not inline with the convention of Bootstrap, this is a primary part of the Material Design methodology where most of our structure is coming from.

1. Make the JS automatically work on all `btn` classes
2. Make an exclusion class `btn-no-ripple` or similar
3. Update our documentation in the gh-pages branch to reflect this change
4. Update our Ripple example in gh-pages to show the exclusion class
5. Update all examples and confirm as working

cc @pmmck

**Comment by RachelRVasquez** [comment]
Submitted a PR for each master/gh-pages:

https://github.com/JDRF/design-system/pull/69

https://github.com/JDRF/design-system/pull/70

**Comment by fuhton** [comment]
Merged and confirmed.
