### ISSUE TITLE
IE9 | Ripple/Loading animation changes

### ISSUE THREAD

**Issue by fuhton** [JDRF/design-system#67]
Work in #66 needs to be completed first.

1. Disable ripple for IE9. 
    - With the change of Ripple being applied to all classes by default, I'd like to use a REUSABLE browser checker to determine if IE9 or lower.
2. Loading animation (as #55 ) should be swapped out for a "Loading..." text if possible.

cc @pmmck

**Comment by RachelRVasquez** [comment]
@fuhton 
Submitted a PR for removing the ripple in IE 9/8:

https://github.com/JDRF/design-system/pull/71

I'd like to complete the loading animation on the original issue:

https://github.com/JDRF/design-system/issues/55

**Comment by RachelRVasquez** [comment]
@fuhton 

Also submitted an additional PR to update documentation for the ripple effect's browser support.

https://github.com/JDRF/design-system/pull/72

**Comment by fuhton** [comment]
Merged and confirmed complete.
