### ISSUE TITLE
Ensure declaration ordering follows best practices.

### ISSUE THREAD

**Issue by magnificode** [JDRF/design-system#7]
Just an organizational piece, especially on lengthier classes (i.e https://github.com/JDRF/design-system/blob/master/src/scss/_buttons.scss#L3) it would be helpful to either alphabetize the declarations or order them by type (Positioning, Box model, Typography, Visual).

https://10up.github.io/Engineering-Best-Practices/css/#declaration-ordering

**Comment by RachelRVasquez** [comment]
Re-organized the styles on master. Let me know if you see anything else @magnificode. Thanks.

https://github.com/JDRF/design-system/commit/0f2c6f5d0490f4e26f0017eb9ed0090c73786a97

**Comment by magnificode** [comment]
Looks great, thanks!!
