### ISSUE TITLE
Add new JS menu item and Ripple JS file

### ISSUE THREAD

**Issue by fuhton** [JDRF/design-system#75]
1. Add a new JS menu item (similar to Component/Content).
2. Add in a docs for using Ripple.js

**Comment by fuhton** [comment]
@pmmck If I were to add in some docs around our JS, where would that fit into the menu hierarchy?

**Comment by pmmck** [comment]
@fuhton how about creating a new parent section titled Get Started and include Download and Javascript, or whatever, as child pages underneath?

**Comment by fuhton** [comment]
@pmmck Makes sense.

**Comment by RachelRVasquez** [comment]
@fuhton Commented on the PR.

**Comment by RachelRVasquez** [comment]
@fuhton Merged.

**Comment by fuhton** [comment]
Merged. JS item has been added. Docs will need to be built out.
