### ISSUE TITLE
Proper heading heirarchy with heading classes for cards

### ISSUE THREAD

**Issue by RachelRVasquez** [JDRF/design-system#85]
I was reviewing the markup for the cards on the demo page:

http://jdrf.github.io/design-system/dist/components.html#cards

And I noticed the featured card is using H4s/H6s. I'd like to discourage overusing headings and using them out of order. I'd like to use the proper headings for the order of the page it's on and take advantage of the heading classes if we want to use a style from a different heading: `.ds-h1, .ds-h2, .ds-h3...`

Can we update the markup to be this instead:

```
<div class="ds-card-block">
	<h3 class="ds-card-title ds-h4">Walgreen's Flu Shot</h3>
	<p class="ds-card-subtitle ds-text-muted">October 10 - April 15</p>
	<p class="ds-card-subtitle ds-text-muted">Mission St. Walgreens</p>
</div>
```

We can also add a note about swapping the H3 if necessary to follow proper heading order while still using the `.ds-h4` class for styling.

Same for the last card using H2/H4, let's remove that H4 above the "Adult Type 1 and Type 1.5..."

```
<div class="ds-card ds-card-program">
	<div class="ds-card-block">
		<p class="ds-card-subtitle">MAY 4</p>
		<h2 class="ds-card-title">Adult Type 1 and Type 1.5 Diabetes Support Group</h2>
		<p class="ds-card-location">Kaiser Hospital, Santa Rosa, CA</p>
	</div>
	<div class="ds-card-block">
		<div class="ds-card-category">Support</div>
	</div>
</div>
```

**Comment by briansaycocie** [comment]
@RachelRVasquez the title/subtitle markup was carried over from [Bootstrap's Card examples](https://v4-alpha.getbootstrap.com/components/card/#content-types), but I agree it would be better to utilize the heading classes.

I've submitted a pull request here: #88

**Comment by RachelRVasquez** [comment]
@briansaycocie The PR looks good to merge on my end. Waiting on any input from @fuhton as well and if none, we can get this merged in Monday.

**Comment by RachelRVasquez** [comment]
@briansaycocie @fuhton Just found something we may need to tweak. Now that we are applying heading classes, the headings have bottom margins that throw off the measurements we're seeing in the designs. So if I throw a `.ds-h5` on the `.ds-card-header` div, it adds margin so the spacing around the content below it is now off from the designs. Do we want to edit the DS to remove margins within cards when using heading classes or handle margins in a case by case basis where in projects, we'd just have to overwrite the margin styles if necessary?

**Comment by fuhton** [comment]
Let's submit a PR to remove bottom margins from heading classes when inside of `ds-card-header`

**Comment by RachelRVasquez** [comment]
@fuhton 

PR submitted:

https://github.com/JDRF/design-system/pull/94

**Comment by fuhton** [comment]
Merged and confirmed.
