### ISSUE TITLE
Remove class from Content Cards' text editor controlled content

### ISSUE THREAD

**Issue by RachelRVasquez** [JDRF/design-system#86]
Referencing the "Content Cards" on the demo:

http://jdrf.github.io/design-system/dist/components.html#cards

There's a `ds-card-text` class that is being applied to the paragraph tag. Assuming this card will be used for the WordPress text editor, we have to assume that:

1. No classes will be added to text elements since they're coming from the wysiwyg unless they're WP defaults
2. There will be other elements aside from paragraphs in this area.

Let's apply any styles to a wrapper rather than specific elements in the content. It looks like this class is only being used to remove the margin from the last paragraph.

**Comment by RachelRVasquez** [comment]
@fuhton 

Two PRs submitted, one for styles, another for markup updates on io:

https://github.com/JDRF/design-system/pull/95

https://github.com/JDRF/design-system/pull/96

**Comment by fuhton** [comment]
Merged and confirmed.
