### ISSUE TITLE
Location card address element

### ISSUE THREAD

**Issue by RachelRVasquez** [JDRF/design-system#87]
Let's swap the `address` element for something more generic since this is being used for external addresses.

Demo: http://jdrf.github.io/design-system/dist/components.html#cards

Address Ref: http://html5doctor.com/the-address-element/

**Comment by RachelRVasquez** [comment]
@briansaycocie Both PRs look good to merge on my end. Waiting on any input from @fuhton as well and if none, we can get this merged in Monday.

**Comment by fuhton** [comment]
Merged and reviewed. Closing.
