### ISSUE TITLE
Padding adjustment to ds-card-header

### ISSUE THREAD

**Issue by RachelRVasquez** [JDRF/design-system#92]
The padding in `.ds-card-header` is currently:

`padding: 0.75rem 1.25rem;`

The designs say they should be 10px top/bottom and 24px left/right. Let's adjust this to:

`padding: 0.625rem 1.5rem;`

The designs are a bit confusing because depending on what you click, it can either be 10px or 12px top/bottom. If I click "Our partners promotions..." and then hover over the container's bottom edge, it'll read 10px. Taking the line-height into consideration with how the grey line aligns with the bottom of the banner behind the card, 10px seems to be the intended measurement.

We also want to match the padding on `..ds-card-block` to 24px (1.5rem) as well so the content will align with the left edge of the `.ds-card-header` content.

**Comment by RachelRVasquez** [comment]
PR submitted:

https://github.com/JDRF/design-system/pull/93

**Comment by fuhton** [comment]
Merged and confirmed.
