### ISSUE TITLE
Add heading classes to card headers where applicable

### ISSUE THREAD

**Issue by RachelRVasquez** [JDRF/design-system#97]
It looks like the card headers in the designs are 16px/24px and are Gotham Medium - which is the same style as the H5 heading. Let's assume we're adding the `.ds-h5` classes to these areas and updated the markup on gh-pages to reflect that.

The designs also specify the color of this text to be `rgba(0, 0, 0, 0.54);`. It looks like we're using `#818a91` instead. Let's update the card styles so it uses the RGB color instead and is consistent with the text color palette on io:

http://jdrf.github.io/design-system/dist/content.html#colors

**Comment by pmmck** [comment]
@RachelRVasquez this is a philosophical question: wouldn't it be more modular if we used .card-header instead of .h5? 

cc @briansaycocie @fuhton

**Comment by RachelRVasquez** [comment]
@pmmck I agree - we can also eliminate the use of the `.ds-text-muted`class and since all card headers are the same style except the archive featured card (w/ the slanted hero) where the line-height is 16 instead of 24px, we can apply the font size/line height/color to the `.card-header`. @fuhton Thoughts?

**Comment by fuhton** [comment]
I agree with Patrick's suggestion as well as your suggestion. @RachelRVasquez Let's add a PR for this change.

**Comment by RachelRVasquez** [comment]
@fuhton 

I've updated DS so we're not using `.ds-text-muted` or `.ds-h5` for the `.card-header`. Instead the font size/line height/color have been applied to the card header. I've also remove the `.ds-text-muted` class from everywhere else and applied styles to the card subtitles. We should only be using heading classes now on headings where we want to change the default heading style.

https://github.com/JDRF/design-system/pull/98

https://github.com/JDRF/design-system/pull/99

Also replaced the hashes in links with hash bangs to be consistent with our side navigation examples.

**Comment by fuhton** [comment]
Merged and confirmed.
